# kubectl apply -f pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  containers:
    - name: sample-app
      image: edosyhtptra/sample-app:v1.1
      ports:
        - containerPort: 8080
